"""add file mapping template

Revision ID: 1687461931eb
Revises: 685490bb2a04
Create Date: 2026-05-18 17:15:25.557127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1687461931eb'
down_revision = '685490bb2a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_mapping_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('target_module', sa.String(length=64), nullable=True),
    sa.Column('mapping_data', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_file_mapping_template_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_mapping_template'))
    )
    with op.batch_alter_table('file_mapping_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_mapping_template_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_mapping_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_mapping_template_name'))

    op.drop_table('file_mapping_template')
    # ### end Alembic commands ###
