"""add waha instance

Revision ID: 685490bb2a04
Revises: d266ceaa7ef6
Create Date: 2026-05-18 12:02:59.822626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685490bb2a04'
down_revision = 'd266ceaa7ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waha_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('api_url', sa.String(length=256), nullable=True),
    sa.Column('api_key', sa.String(length=128), nullable=True),
    sa.Column('session_name', sa.String(length=128), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waha_instance'))
    )
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waha_instance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_message_log_waha_instance_id_waha_instance'), 'waha_instance', ['waha_instance_id'], ['id'])

    # ### end Alembic commands ###
    
    # --- Data Migration ---
    connection = op.get_bind()
    
    # Read old settings
    settings_query = connection.execute(sa.text("SELECT `key`, `value` FROM setting WHERE `key` IN ('evo_api_url', 'evo_api_key', 'evo_instance')"))
    settings = {row[0]: row[1] for row in settings_query}
    
    api_url = settings.get('evo_api_url')
    session_name = settings.get('evo_instance')
    
    if api_url and session_name:
        api_key = settings.get('evo_api_key', '')
        connection.execute(sa.text(
            "INSERT INTO waha_instance (name, api_url, api_key, session_name, is_default, status) "
            "VALUES (:name, :url, :key, :session, :is_default, :status)"
        ), {
            'name': 'Servidor Padrão (Migrado)',
            'url': api_url,
            'key': api_key,
            'session': session_name,
            'is_default': True,
            'status': 'disconnected'
        })
        
        # Delete old settings to clean up
        connection.execute(sa.text("DELETE FROM setting WHERE `key` IN ('evo_api_url', 'evo_api_key', 'evo_instance')"))
    # ----------------------


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_message_log_waha_instance_id_waha_instance'), type_='foreignkey')
        batch_op.drop_column('waha_instance_id')

    op.drop_table('waha_instance')
    # ### end Alembic commands ###
