"""add client fields and store

Revision ID: 77c0b069e97f
Revises: 
Create Date: 2026-04-15 10:45:34.368161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c0b069e97f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('preferred_store_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referred_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preferred_channel', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('lead_source', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_purchase_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('purchase_frequency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ltv', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loyalty_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tier', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('points_expiration', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('badges', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('opt_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('opt_in_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_usage_purpose', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('consent_channel', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_client_cpf'), ['cpf'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_client_preferred_store_id_store'), 'store', ['preferred_store_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_client_referred_by_id_user'), 'user', ['referred_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_client_referred_by_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_client_preferred_store_id_store'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_client_cpf'))
        batch_op.drop_column('consent_channel')
        batch_op.drop_column('data_usage_purpose')
        batch_op.drop_column('opt_in_date')
        batch_op.drop_column('opt_in')
        batch_op.drop_column('badges')
        batch_op.drop_column('points_expiration')
        batch_op.drop_column('tier')
        batch_op.drop_column('loyalty_points')
        batch_op.drop_column('ltv')
        batch_op.drop_column('purchase_frequency')
        batch_op.drop_column('last_purchase_date')
        batch_op.drop_column('lead_source')
        batch_op.drop_column('preferred_channel')
        batch_op.drop_column('referred_by_id')
        batch_op.drop_column('preferred_store_id')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('address')
        batch_op.drop_column('cep')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
