"""client_unique_constraints_fix

Revision ID: d266ceaa7ef6
Revises: fe68cbd2238b
Create Date: 2026-04-15 14:36:31.923060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd266ceaa7ef6'
down_revision = 'fe68cbd2238b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_public_id'))
        batch_op.drop_index(batch_op.f('ix_client_phone'))

    # ### end Alembic commands ###
