"""messaging_models

Revision ID: fe68cbd2238b
Revises: 77c0b069e97f
Create Date: 2026-04-15 12:15:29.276327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe68cbd2238b'
down_revision = '77c0b069e97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_template'))
    )
    with op.batch_alter_table('message_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_template_name'), ['name'], unique=True)

    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('api_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_message_log_client_id_client')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_message_log_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_log')
    with op.batch_alter_table('message_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_template_name'))

    op.drop_table('message_template')
    # ### end Alembic commands ###
